import styles from './styles/globals.css'
import { Inter } from 'next/font/google'
import Header from './components/header/Header'
import Footer from './components/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, metadata }) {
  return (
    <html lang="en">
      <head>
        {metadata}
      </head>
      <body className={inter.className}>
        <Header />
        <main className="container">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
